version: '3.7'

services:
  landingpage:
    image: crangelp/landingpage:v2.2
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    networks:
      - network_swarm_public

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.landingpage.rule=Host(`primestratus.com.br`)
        - traefik.http.routers.landingpage.entrypoints=websecure
        - traefik.http.routers.landingpage.tls.certresolver=letsencryptresolver
        - traefik.http.services.landingpage.loadbalancer.server.port=8254
        - traefik.http.services.landingpage.loadbalancer.passHostHeader=true

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
